### ISSUE TITLE
release ready?

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_movebase#2]
This looks pretty solid for a first release? Shall I at least include it in jenkins for devel build to see if it works? If so, please reply and assign to me. 

I want to sort out the problem that currently calibrate_chest is duplictated in https://github.com/strands-project/scitos_common/tree/hydro-devel/calibrate_chest and we need an orchestrated action to resolve this.

**Comment by nilsbore** [comment]
So, are we OK to have scitos_common depend on strands_movebase via this include: https://github.com/strands-project/scitos_common/blob/hydro-devel/scitos_description/launch/scitos_state_publisher.launch ? I don't see any way around it if we want an up to date transform of the chest camera every time the robot starts.

I'll create a pull request to remove the calibrate_chest package.

**Comment by hawesie** [comment]
I think that dependency is the wrong way around. Scitos stuff can't depend on strands although the other way around is fine. =

**Comment by nilsbore** [comment]
Ok, so how should we do this? I don't see any problem with having the package in a more general repo since it's not specific to strands_movebase.

**Comment by nilsbore** [comment]
Or should we simply launch the chest_calibration_publisher together with the 3d obstacle avoidance?

**Comment by nilsbore** [comment]
What do you guys say, @marc-hanheide @hawesie ?

**Comment by hawesie** [comment]
I'm not 100% clear on what's going on. Can you summarise the issue?

**Comment by nilsbore** [comment]
The problem is that `chest_calibration_publisher` was previously run at robot startup, in `scitos_state_publisher.launch`. As discussed in https://github.com/strands-project/scitos_2d_navigation/issues/43, we decided to move it to this repository and launch it at startup. However, since `scitos_description` can't depend on `strands_movebase/calibrate_chest` I don't know where to put it. My suggestion was to launch it in `movebase.launch`, together with the other movebase things since we are only using the chest camera here atm. However, it would be nicer to launch it earlier on since someone might want to use the point cloud eventually.

**Comment by hawesie** [comment]
I think our decision was the the chest cam was strands not scitos therefore we should launch `scitos_state_publisher.launch` without the chest cam at all (but publishing all the other bits), and run the the calibrate chest separately, e.g. from here. Alternatively we only launch one launch file, the one from `strands_movebase` but this should include `scitos_state_publisher.launch` and add in the cam stuff. Either way we need two separate launch files.

**Comment by nilsbore** [comment]
Ok, I will have to investigate if it's possible to have multiple state publishers since the chest camera is part of the big urdf atm. Maybe it would make more sense with a `strands_common` repo or similar with `strands_description` and `strands_state_publisher.launch` including `scitos_state_publisher.launch` but also a state publisher for the chest camera frames. Maybe `calibrate_chest` could go in that repo.

Either way I will try to implement a separate description for the chest camera frames then.

**Comment by hawesie** [comment]
Great, thanks.

**Comment by nilsbore** [comment]
Ok, I have 2 pulls that should resolve this: https://github.com/strands-project/strands_movebase/pull/3 and https://github.com/strands-project/scitos_common/pull/40. I'll try them out tomorrow but just publishing the transforms like this seems to be working.

**Comment by marc-hanheide** [comment]
I just found there's a dependency into the deprecated `scitos_2d_navigation` Is that by accident?

**Comment by nilsbore** [comment]
No it's not by accident, basically it works the same way as before, if you provide `with_camera:=false` tp `movebase.launch` you will get `scitos_2d_nav.launch` instead of the 3d obstacle avoidance in `strands_movebase`. Also, we use the `amcl.launch` in `scitos_2d_navigation`.

**Comment by nilsbore** [comment]
I didn't think that it would be deprecated?

**Comment by marc-hanheide** [comment]
ah, my bad then. You are right. I shall release it then, so we can make further progress.

**Comment by marc-hanheide** [comment]
scitos_2d_navigation is released, both hydro and indigo. So, now we can work towards this one

**Comment by hawesie** [comment]
Good stuff.

**Comment by marc-hanheide** [comment]
I put this repo on jenkins as well, it builds nicely, so I'd say, ready for release?

https://lcas.lincoln.ac.uk/jenkins/job/devel-hydro-strands_movebase/

https://lcas.lincoln.ac.uk/jenkins/job/devel-indigo-strands_movebase/

**Comment by marc-hanheide** [comment]
released! build is running! I'll close this for now

**Comment by nilsbore** [comment]
Cool!
