### ISSUE TITLE
[strands_navfn] is not melodic-ready

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_movebase#73]
as https://lcas.lincoln.ac.uk/buildfarm/job/Mdev__strands_movebase__ubuntu_bionic_amd64/ shows, `strands_navfn` refuses to compile for ROS melodic.

The problem is a lot of API changes in `move_base`: https://github.com/paulbovbel/frontier_exploration/issues/38#issuecomment-449415389

So, question: What does `strands_navfn` offer that the standard `navfn` doesn't? Can it be removed?

**Comment by hawesie** [comment]
Hmm... this wasn't me. Perhaps @nilsbore remembers?

**Comment by bfalacerda** [comment]
This was me. The functionality it provides is always looking at the `default_tolerance` parameter before planning. This would allow us to plan to influence areas even if there was an obstacle in the middle. We need it to be dynamically checked before planning because the tolerance for intermediary nodes should be greater than 0  (e.g. 1m) but for target nodes it should be 0.0

Commit below shows the main difference:

https://github.com/strands-project/strands_movebase/commit/cf3b8a3aac4e13221e9227992d56063f97438133

**Comment by marc-hanheide** [comment]
Thanks @bfalacerda I wonder if this is indeed still needed. It's a bit unfortunate this hasn't been a fork of the original, difficult to merge from upstream in this case, I reckon.

**Comment by bfalacerda** [comment]
yeah, it wasn't the best way to do it... I'd say ignore  this package and if we end up needing it we do the fork and re-do the change, it's easy enough.

I think the only thing that need to be changed to stop using this package is https://github.com/strands-project/strands_movebase/blob/indigo-devel/strands_movebase/strands_movebase_params/move_base_params.yaml#L1

**Comment by marc-hanheide** [comment]
see #74

**Comment by marc-hanheide** [comment]
FYI: our melodic release is slowly taking shape... https://github.com/LCAS/rosdistro/wiki/repos-melodic in case @hawesie or @bfalacerda want to update Bob and/or Betty.
